### ISSUE TITLE
segmentation fault (core dumped) with cuckaroo_cpu_avx2_xx plugin on ubuntu 18.04

### ISSUE THREAD

**Issue by hadv** [mimblewimble/grin-miner#75]
When running with `cuckaroo_cpu_avx2_xx` miner plugins, grin-miner always be stop with below error

```
segmentation fault (core dumped)
```

it's no problem with miner plugins: `cuckatoo_mean_cpu_avx2_31` and `cuckaroo_cpu_compat_29`

**Comment by bladedoyle** [comment]
It crashes for me on both i7 and i9 CPU.  The stack trace shows:

```
Thread 9 "grin-miner" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffef13c8700 (LWP 17730)]
edgetrimmer::genUVnodes (this=this@entry=0x7ffff540e000, id=id@entry=0)
    at /home/bdoyle/tmp/grin-miner/cuckoo-miner/src/cuckoo_sys/plugins/cuckoo/src/cuckaroo/mean.hpp:333
333               _mm256_store_si256((__m256i *)(buf + e),     XOR(XOR(v0,v1),XOR(v2,v3)));
(gdb)
```

**Comment by tromp** [comment]
Should be fixed by https://github.com/tromp/cuckoo/commit/7454620fc3ca42f7cbc43c53b5a501fc3a3ca350

To fix this before the next grin-miner update, you can run
 git submodule update --remote --recursive
and rebuild grin-miner

**Comment by hadv** [comment]
> Should be fixed by [tromp/cuckoo@7454620](https://github.com/tromp/cuckoo/commit/7454620fc3ca42f7cbc43c53b5a501fc3a3ca350)
> 
> To fix this before the next grin-miner update, you can run
> git submodule update --remote --recursive
> and rebuild grin-miner

it seems I still have problem with `cuckaroo_cpu_avx2_29` miner plugin

**Comment by tromp** [comment]
Note that I needed a fix in another place too. Are you using https://github.com/tromp/cuckoo/commit/a074dcc44240e09d8494b75b5bbab9d674d92a68 or a later commit?

**Comment by hadv** [comment]
> Note that I needed a fix in another place too. Are you using [tromp/cuckoo@a074dcc](https://github.com/tromp/cuckoo/commit/a074dcc44240e09d8494b75b5bbab9d674d92a68) or a later commit?

I will recheck later. I just run `git submodule update --remote --recursive` and rebuild

**Comment by hadv** [comment]
thanks, it worked with this commit https://github.com/tromp/cuckoo/commit/4ec7302515b95178a04652985d078dbb38bbde7d

**Comment by tromp** [comment]
Ok, feel free to close this issue.
